import subprocess
import os
import sys
import shutil

# ========= CONFIG =========
ANTLR_JAR = "/usr/local/lib/antlr-4.13.2-complete.jar"

GRAMMAR_DIR = "grammar"
OUTPUT_DIR = "generated"

LEXER_FILE = "SentenceLexer.g4"
PARSER_FILE = "SentenceParser.g4"
# ==========================


def check_java():
    """Check if Java is installed"""
    try:
        result = subprocess.run(
            ["java", "-version"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print("✓ Java is installed")
            return True
        else:
            print("✗ Java is not installed or not in PATH")
            return False
    except FileNotFoundError:
        print("✗ Java is not installed")
        return False


def check_antlr_jar():
    """Check if ANTLR JAR file exists"""
    if os.path.exists(ANTLR_JAR):
        print(f"✓ ANTLR JAR found at: {ANTLR_JAR}")
        return True
    else:
        print(f"✗ ANTLR JAR not found at: {ANTLR_JAR}")
        print("  Please download from: https://www.antlr.org/download.html")
        return False


def clean_output_dir():
    """Clean the output directory before generation"""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(base_dir, OUTPUT_DIR)
    
    if os.path.exists(output_path):
        print(f"🧹 Cleaning output directory: {output_path}")
        shutil.rmtree(output_path)
    
    os.makedirs(output_path, exist_ok=True)
    
    # Create __init__.py for Python package
    init_file = os.path.join(output_path, "__init__.py")
    with open(init_file, "w") as f:
        f.write("# Generated by ANTLR\n")


def run_antlr(grammar_file: str):
    """Run ANTLR on a grammar file"""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    grammar_path = os.path.join(base_dir, GRAMMAR_DIR, grammar_file)
    output_path = os.path.join(base_dir, OUTPUT_DIR)

    if not os.path.exists(grammar_path):
        print(f"❌ Grammar file not found: {grammar_path}")
        sys.exit(1)

    cmd = [
        "java",
        "-jar",
        ANTLR_JAR,
        "-Dlanguage=Python3",
        "-visitor",
        "-no-listener",
        "-o",
        output_path,
        grammar_path
    ]

    print(f"▶ Generating from {grammar_file} ...")
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )
        
        if result.stdout:
            print(result.stdout)
        
        print(f"✓ Successfully generated from {grammar_file}")
        
    except subprocess.CalledProcessError as e:
        print(f"❌ Error generating from {grammar_file}")
        print(f"Error output: {e.stderr}")
        sys.exit(1)


def verify_output():
    """Verify that all expected files were generated"""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(base_dir, OUTPUT_DIR)
    
    expected_files = [
        "SentenceLexer.py",
        "SentenceParser.py",
        "SentenceLexer.tokens",
        "SentenceParser.tokens"
    ]
    
    print("\n📋 Verifying generated files:")
    all_present = True
    
    for filename in expected_files:
        filepath = os.path.join(output_path, filename)
        if os.path.exists(filepath):
            size = os.path.getsize(filepath)
            print(f"  ✓ {filename} ({size} bytes)")
        else:
            print(f"  ✗ {filename} - NOT FOUND")
            all_present = False
    
    return all_present


def print_usage_example():
    """Print example usage after successful generation"""
    print("\n📚 Usage Example:")
    print("=" * 60)
    print("""
from analysis.parser_runner import parse_sentence
from analysis.analyzer import analyze_sentence

# Parse a sentence
text = "I'm sorry, could you please help me with this?"
tokens = parse_sentence(text)
print("Tokens:", tokens)

# Analyze the sentence
analysis = analyze_sentence(text)
print("Style:", analysis["style"])
print("Politeness Score:", analysis["politeness_score"])
print("Suggestions:", analysis["suggestions"])
    """)
    print("=" * 60)


def main():
    """Main function to run ANTLR generation"""
    print("=" * 60)
    print("🚀 ANTLR Grammar Generator for Communication Analysis")
    print("=" * 60)
    print()
    
    # Check prerequisites
    if not check_java():
        print("\n❌ Please install Java to continue")
        sys.exit(1)
    
    if not check_antlr_jar():
        print("\n❌ Please install ANTLR JAR file")
        sys.exit(1)
    
    print()
    
    # Clean output directory
    clean_output_dir()
    
    # Generate from grammar files
    print("\n📝 Generating Python code from grammar files...")
    print("-" * 60)
    
    run_antlr(LEXER_FILE)
    run_antlr(PARSER_FILE)
    
    # Verify output
    print()
    if verify_output():
        print("\n✅ ANTLR generation completed successfully!")
        print(f"📂 Output directory: {os.path.join(os.path.dirname(os.path.abspath(__file__)), OUTPUT_DIR)}")
        print_usage_example()
    else:
        print("\n⚠️ Some files were not generated correctly")
        sys.exit(1)


if __name__ == "__main__":
    main()